stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  COMPOSE_PROJECT_NAME: muskmonitor

build:
  stage: build
  image: docker:latest
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker info
  script:
    # Build the Docker images locally
    - docker build -t mongo:latest -e MONGO_INITDB_ROOT_USERNAME=root -e MONGO_INITDB_ROOT_PASSWORD=root_password sys-src/stock-database
    - docker build -t react-frontend:latest -f sys-src/muskmonitor-frontend/Dockerfile sys-src/muskmonitor-frontend
    - docker build -t flask-backend:latest -f sys-src/muskmonitor-backend/Dockerfile sys-src/muskmonitor-backend
    - docker build -t nginx:latest -f sys-src/nginx/Dockerfile sys-src/nginx
  only:
    - main

test:
  stage: test
  image: docker:latest
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    # Run database service
    - docker run -d --name test-database cr.weaviate.io/semitechnologies/weaviate

    # Run Flask backend tests
    - docker build -t flask-tests -f sys-src/muskmonitor-backend/Dockerfile sys-src/muskmonitor-backend
    - docker run --rm --name flask-tests flask-tests pytest --maxfail=1 --disable-warnings

    # Run React frontend tests
    - docker build -t react-tests -f sys-src/muskmonitor-frontend/Dockerfile --target build sys-src/muskmonitor-frontend
    - docker run --rm --name react-tests react-tests npm run test -- --run

    # Cleanup
    - docker stop test-database
    - docker rm test-database
  only:
    - main

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:27.0-dind
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)

    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - ssh-keyscan 130.61.36.199 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    # Clean up old files before copying new ones
    - 'ssh -o StrictHostKeyChecking=no ubuntu@130.61.36.199 "rm -rf /opt/muskmonitor/sys-src"'
    # Copy the files to the server using scp
    - 'scp -o StrictHostKeyChecking=no -r sys-src ubuntu@130.61.36.199:/opt/muskmonitor'
    # SSH into the server and run docker compose
    - 'ssh -o StrictHostKeyChecking=no ubuntu@130.61.36.199 "cd /opt/muskmonitor/sys-src && sudo docker compose down && sudo docker compose up -d --build"'
  only:
    - main