stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  COMPOSE_PROJECT_NAME: muskmonitor

build:
  stage: build
  image: docker:latest
  services:
    - docker:19-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker info
  script:
    # Build the Docker images locally
    - docker build -t react-frontend:latest -f sys-src/muskmonitor-frontend/Dockerfile sys-src/muskmonitor-frontend
    - docker build -t nginx:latest -f sys-src/nginx/Dockerfile sys-src/nginx
  only:
    - main

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:19-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker info
  script:
    - cp sys-src/docker-compose.yml /opt/muskmonitor
    - cd /opt/muskmonitor
    # Start or restart the Docker Compose application
    - docker-compose down
    - docker-compose up -d --build
  only:
    - main