stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  COMPOSE_PROJECT_NAME: muskmonitor

build:
  stage: build
  image: docker:latest
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker info
  script:
    # Build the Docker images locally
    - docker build -t react-frontend:latest -f sys-src/muskmonitor-frontend/Dockerfile sys-src/muskmonitor-frontend
    - docker build -t nginx:latest -f sys-src/nginx/Dockerfile sys-src/nginx
  only:
    - main

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:27.0-dind
  script:
    - mkdir -p /opt/muskmonitor
    - cp -r sys-src /opt/muskmonitor
    - cd /opt/muskmonitor/sys-src

    # Copy the files to the server using scp
    - 'scp -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no -r /opt/muskmonitor ubuntu@130.61.36.199:/opt/muskmonitor'

    # SSH into the server and run docker-compose
    - 'ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ubuntu@130.61.36.199 "cd /opt/muskmonitor/sys-src && docker compose down && docker compose up -d --build"'
  only:
    - main