services:
  # flask-backend:
  #   build: ./backend
  #   container_name: flask-backend
  #   ports:
  #    - "5000:5000"

  react-frontend:
    build: ./muskmonitor-frontend
    container_name: react-frontend
    ports:
      - "3001:80"  # Mapping external port 3001 to internal port 80

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      #- flask-backend
      - react-frontend